worlddynamics/WorldDynamics.jl

README.md

Fixes #34
The link to the stable version is currently broken since we don't have any release, but will automatically link to the latest one.

Adding badges pointing to the documentation

---

README.md

Adding *How to cite this work*

---

docs/src/tutorial.md

I have updated the documentation.

Updated docs with scenarios

---

src/World3/pollution/plots.jl
src/World3/population/pop15/plots.jl
src/solvesystems.jl

Only figures remaining are those of #73 .

Implementing figures that require equation change

---

src/World3/population/pop1/plots.jl
src/World3/population/pop15/plots.jl
src/World3/population/pop4/plots.jl

Fix values of yearly variables

---

README.md

Organizing logos in the README

---

src/solvesystems.jl

This allows us to use a solver that accepts keyword arguments without creating a system and a problem externally.
Fixes #87

Add kwargs to solve function

---

README.md

Add "Getting Started" section to the README

---

src/World3/agriculture/plots.jl
src/World3/capital/plots.jl
src/World3/nonrenewable/plots.jl
src/World3/pollution/plots.jl
src/World3/population/pop1/plots.jl
src/World3/population/pop15/plots.jl
src/World3/population/pop4/plots.jl
src/World3/world3/plots.jl

Treating #84 with the updated argument parameters.

Documenting figs

---

src/World3/capital/plots.jl

Fix error in Figure 3.46

---

src/World2/world2/plots.jl
src/World2/world2/scenarios.jl
test/world2/figures.jl

Implement figures from chapter 4 of World2 

---

src/World2/world2/plots.jl
src/World2/world2/scenarios.jl
test/world2/figures.jl

Close issue  #110 and docstrings chapter 4

Figures chapter 6

---

src/World3_91/World3_91.jl
src/World3_91/world3_91/plots.jl
src/World3_91/world3_91/scenarios.jl
src/WorldDynamics.jl
test/runtests.jl
test/world3_91/figures.jl
test/world3_91/scenarios.jl

Implement standard scenarios of World3-91 update.
Related to #129

World3-91 update

---

docs/src/tutorial.md

Add to the documentation a description on how to update the model with modern data.
Related to #27.

Add modern data description to the documentation

---

docs/src/world2.md
src/World2/agricultureinvestment/subsystems.jl
src/World2/capitalinvestment/subsystems.jl
src/World2/naturalresources/subsystems.jl
src/World2/pollution/subsystems.jl
src/World2/population/subsystems.jl
src/World2/qualitylife/subsystems.jl

Addressing Issue #99 where we incorporate metadata for parameters and variables of the World2 model.

Variables metadata for World2

---

src/World3_03/NewEquations.jl
src/World3_03/World3_03.jl
src/World3_03/world3_03/plots.jl
src/World3_03/world3_03/scenarios.jl
src/World3_91/world3_91/scenarios.jl
src/WorldDynamics.jl
test/runtests.jl
test/world3_03/figures.jl
test/world3_03/scenarios.jl

Implement standard scenario of World3-03 update.
Related to #96

World3-03 update

---

docs/src/source.md

Add missing docs of World3's Pollution system

---

src/World1/world1/plots.jl

Add docstrings to the World1 model

---

src/World1B/World1B.jl
src/World1B/world1b/initialisations.jl
src/World1B/world1b/parameters.jl
src/World1B/world1b/plots.jl
src/World1B/world1b/scenarios.jl
src/World1B/world1b/subsystems.jl
src/World1B/world1b/tables.jl
src/WorldDynamics.jl
test/runtests.jl
test/world1b/figures.jl
test/world1b/scenarios.jl

Implement World1B update

---

src/Earth4All/Earth4All.jl

We fix a missing derivative as detected by @piluc.

Update E4A with missing derivative

---

docs/make.jl

Update docs repository url

---

test/functions.jl
test/runtests.jl

Add unit tests to utility functions

---

src/functions.jl

Fix interpolate function

---

docs/src/source.md

Add missing docs in webpage

---

src/Earth4All/Earth4All.jl
src/Earth4All/plots.jl
src/functions.jl

Improve variable names

---

src/World1A/world1a/scenarios.jl
src/World1B/world1b/scenarios.jl
src/World2/world2/scenarios.jl
src/World3/agriculture/scenarios.jl
src/World3/capital/scenarios.jl
src/World3/nonrenewable/scenarios.jl
src/World3/pollution/scenarios.jl
src/World3/pollution/subsystems.jl
src/World3/population/pop1/scenarios.jl
src/World3/population/pop15/scenarios.jl
src/World3/population/pop4/scenarios.jl
src/World3/world3/plots.jl
src/World3/world3/scenarios.jl
src/solvesystems.jl
test/runtests.jl
test/solvesystems.jl

This PR adds the `variable_connections` function and applies it to the scenarios.

Calculate subsystem connections automatically
